apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Namespace
  metadata:
    name: nodejs
- apiVersion: v1
  kind: Service
  metadata:
    name: nodejs
    namespace: nodejs
    labels:
      app: nodejs
      role: web
    annotations:
      external-dns.alpha.kubernetes.io/hostname: nodebackend.deploybytes.com.
  spec:
    type: LoadBalancer
    ports:
    - name: web
      port: 80
      targetPort: web
      protocol: TCP
    selector:
      app: nodejs
      role: web
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    name: nodejs
    namespace: nodejs
  spec:
    replicas: 1
    strategy:
      type: RollingUpdate
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: nodejs
        role: web
    template:
      metadata:
        labels:
          app: nodejs
          role: web
         annotations:
          consul.register/enabled: "true"
          consul.register/service.name: "nodejs_backend"
      spec:
        containers:
        - name: nodejs
          image: qpair/nodejs:1.0.0
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /api/getUsers/1
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /api/getUsers/1
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 5
          ports:
          - name: web
            containerPort: 3001
